### ISSUE TITLE
Нет описания в Readme

### ISSUE THREAD

**Issue by repjov** [Glebbond/theme5#2]
Не понятно как запускать scss, нужно описать

**Comment by Glebbond** [comment]
есть readme, как его нет?

**Comment by repjov** [comment]
У тебя Readme нет в ветке мастер. Ну и редми который пишешь ты, совсем далек от юзерфрендли :)

**Comment by Glebbond** [comment]
а я понял я просто правки все вносил в ветке bundlers и там у меня уже был readme )  поэтому я и удивился
